Repository TheWidlarzGroup/react-native-video, pull requests merged in 2022-05, with the labels that each got.

#2662 fix: improve basic player
  CHANGELOG.md
  examples/basic/android/app/build.gradle
  examples/basic/android/app/src/main/java/com/videoplayer/MainApplication.java
  examples/basic/android/settings.gradle
  examples/basic/package.json
  examples/basic/src/VideoPlayer.android.tsx
  examples/basic/yarn.lock
Labels: documentation

#2551 clarify onProgress documentation
  README.md
Labels: documentation

#2609 Always check for hideShutterView before showing shutterView
  CHANGELOG.md
  android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
Labels: bug, android

#2302 Update Readme to include onBuffer event (#2141)
  README.md
Labels: documentation

#2688 Revert "[Android] fullscreen video"
  README.md
  android-exoplayer/src/main/AndroidManifest.xml
  android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerFullscreenVideoActivity.java
  android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
  android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
  android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
  android-exoplayer/src/main/res/layout/exo_player_control_view.xml
  android-exoplayer/src/main/res/layout/exo_player_fullscreen_video.xml
  android/src/main/AndroidManifest.xml
Labels: android

#2371 Fix volume reset issue in exoPlayer
  android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Labels: bug, android

#2701 docs: removed lumpen-radio example because no longer available on Github
  API.md
Labels: documentation

#2699 added author in package.json
  package.json
Labels: bug
